function asyncGeneratorStep(B,y,K,J,H,F,C){try{var I=B[F](C),D=I.value}catch(L){K(L);return}I.done?y(D):Promise.resolve(D).then(J,H)}function _asyncToGenerator(B){return function(){var y=this,K=arguments;return new Promise(function(J,H){function F(D){asyncGeneratorStep(I,J,H,F,C,"next",D)}function C(D){asyncGeneratorStep(I,J,H,F,C,"throw",D)}var I=B.apply(y,K);F(void 0)})}}
function _typeof(B){_typeof="function"===typeof Symbol&&"symbol"===typeof Symbol.iterator?function(y){return typeof y}:function(y){return y&&"function"===typeof Symbol&&y.constructor===Symbol&&y!==Symbol.prototype?"symbol":typeof y};return _typeof(B)}var _regenerator;
(function(){var B=function(y){function K(a,b,c,m){b=Object.create((b&&b.prototype instanceof H?b:H).prototype);m=new M(m||[]);b._invoke=L(a,c,m);return b}function J(a,b,c){try{return{type:"normal",arg:a.call(b,c)}}catch(m){return{type:"throw",arg:m}}}function H(){}function F(){}function C(){}function I(a){["next","throw","return"].forEach(function(b){a[b]=function(c){return this._invoke(b,c)}})}function D(a,b){function c(d,p,t,w){d=J(a[d],a,p);if("throw"===d.type)w(d.arg);else{var u=d.arg;return(d=
u.value)&&"object"===_typeof(d)&&E.call(d,"__await")?b.resolve(d.__await).then(function(A){c("next",A,t,w)},function(A){c("throw",A,t,w)}):b.resolve(d).then(function(A){u.value=A;t(u)},function(A){return c("throw",A,t,w)})}}var m;this._invoke=function(d,p){function t(){return new b(function(w,u){c(d,p,w,u)})}return m=m?m.then(t,t):t()}}function L(a,b,c){var m=l;return function(d,p){if(m===v)throw Error("Generator is already running");if(m===e){if("throw"===d)throw p;return P()}c.method=d;for(c.arg=
p;;){if(d=c.delegate)if(d=Q(d,c)){if(d===h)continue;return d}if("next"===c.method)c.sent=c._sent=c.arg;else if("throw"===c.method){if(m===l)throw m=e,c.arg;c.dispatchException(c.arg)}else"return"===c.method&&c.abrupt("return",c.arg);m=v;d=J(a,b,c);if("normal"===d.type){m=c.done?e:g;if(d.arg===h)continue;return{value:d.arg,done:c.done}}"throw"===d.type&&(m=e,c.method="throw",c.arg=d.arg)}}}function Q(a,b){var c=a.iterator[b.method];if(c===G){b.delegate=null;if("throw"===b.method){if(a.iterator["return"]&&
(b.method="return",b.arg=G,Q(a,b),"throw"===b.method))return h;b.method="throw";b.arg=new TypeError("The iterator does not provide a 'throw' method")}return h}c=J(c,a.iterator,b.arg);if("throw"===c.type)return b.method="throw",b.arg=c.arg,b.delegate=null,h;c=c.arg;if(!c)return b.method="throw",b.arg=new TypeError("iterator result is not an object"),b.delegate=null,h;if(c.done)b[a.resultName]=c.value,b.next=a.nextLoc,"return"!==b.method&&(b.method="next",b.arg=G);else return c;b.delegate=null;return h}
function R(a){var b={tryLoc:a[0]};1 in a&&(b.catchLoc=a[1]);2 in a&&(b.finallyLoc=a[2],b.afterLoc=a[3]);this.tryEntries.push(b)}function N(a){var b=a.completion||{};b.type="normal";delete b.arg;a.completion=b}function M(a){this.tryEntries=[{tryLoc:"root"}];a.forEach(R,this);this.reset(!0)}function O(a){if(a){var b=a[n];if(b)return b.call(a);if("function"===typeof a.next)return a;if(!isNaN(a.length)){var c=-1;b=function d(){for(;++c<a.length;)if(E.call(a,c))return d.value=a[c],d.done=!1,d;d.value=
G;d.done=!0;return d};return b.next=b}}return{next:P}}function P(){return{value:G,done:!0}}var S=Object.prototype,E=S.hasOwnProperty,G,x="function"===typeof Symbol?Symbol:{},n=x.iterator||"@@iterator",r=x.asyncIterator||"@@asyncIterator",k=x.toStringTag||"@@toStringTag";y.wrap=K;var l="suspendedStart",g="suspendedYield",v="executing",e="completed",h={};x={};x[n]=function(){return this};var f=Object.getPrototypeOf;(f=f&&f(f(O([]))))&&f!==S&&E.call(f,n)&&(x=f);var q=C.prototype=H.prototype=Object.create(x);
F.prototype=q.constructor=C;C.constructor=F;C[k]=F.displayName="GeneratorFunction";y.isGeneratorFunction=function(a){return(a="function"===typeof a&&a.constructor)?a===F||"GeneratorFunction"===(a.displayName||a.name):!1};y.mark=function(a){Object.setPrototypeOf?Object.setPrototypeOf(a,C):(a.__proto__=C,k in a||(a[k]="GeneratorFunction"));a.prototype=Object.create(q);return a};y.awrap=function(a){return{__await:a}};I(D.prototype);D.prototype[r]=function(){return this};y.AsyncIterator=D;y.async=function(a,
b,c,m,d){void 0===d&&(d=Promise);var p=new D(K(a,b,c,m),d);return y.isGeneratorFunction(b)?p:p.next().then(function(t){return t.done?t.value:p.next()})};I(q);q[k]="Generator";q[n]=function(){return this};q.toString=function(){return"[object Generator]"};y.keys=function(a){var b=[],c;for(c in a)b.push(c);b.reverse();return function d(){for(;b.length;){var p=b.pop();if(p in a)return d.value=p,d.done=!1,d}d.done=!0;return d}};y.values=O;M.prototype={constructor:M,reset:function(a){this.next=this.prev=
0;this.sent=this._sent=G;this.done=!1;this.delegate=null;this.method="next";this.arg=G;this.tryEntries.forEach(N);if(!a)for(var b in this)"t"===b.charAt(0)&&E.call(this,b)&&!isNaN(+b.slice(1))&&(this[b]=G)},stop:function(){this.done=!0;var a=this.tryEntries[0].completion;if("throw"===a.type)throw a.arg;return this.rval},dispatchException:function(a){function b(u,A){p.type="throw";p.arg=a;c.next=u;A&&(c.method="next",c.arg=G);return!!A}if(this.done)throw a;for(var c=this,m=this.tryEntries.length-1;0<=
m;--m){var d=this.tryEntries[m],p=d.completion;if("root"===d.tryLoc)return b("end");if(d.tryLoc<=this.prev){var t=E.call(d,"catchLoc"),w=E.call(d,"finallyLoc");if(t&&w){if(this.prev<d.catchLoc)return b(d.catchLoc,!0);if(this.prev<d.finallyLoc)return b(d.finallyLoc)}else if(t){if(this.prev<d.catchLoc)return b(d.catchLoc,!0)}else if(w){if(this.prev<d.finallyLoc)return b(d.finallyLoc)}else throw Error("try statement without catch or finally");}}},abrupt:function(a,b){for(var c=this.tryEntries.length-
1;0<=c;--c){var m=this.tryEntries[c];if(m.tryLoc<=this.prev&&E.call(m,"finallyLoc")&&this.prev<m.finallyLoc){var d=m;break}}d&&("break"===a||"continue"===a)&&d.tryLoc<=b&&b<=d.finallyLoc&&(d=null);c=d?d.completion:{};c.type=a;c.arg=b;return d?(this.method="next",this.next=d.finallyLoc,h):this.complete(c)},complete:function(a,b){if("throw"===a.type)throw a.arg;"break"===a.type||"continue"===a.type?this.next=a.arg:"return"===a.type?(this.rval=this.arg=a.arg,this.method="return",this.next="end"):"normal"===
a.type&&b&&(this.next=b);return h},finish:function(a){for(var b=this.tryEntries.length-1;0<=b;--b){var c=this.tryEntries[b];if(c.finallyLoc===a)return this.complete(c.completion,c.afterLoc),N(c),h}},"catch":function(a){for(var b=this.tryEntries.length-1;0<=b;--b){var c=this.tryEntries[b];if(c.tryLoc===a){a=c.completion;if("throw"===a.type){var m=a.arg;N(c)}return m}}throw Error("illegal catch attempt");},delegateYield:function(a,b,c){this.delegate={iterator:O(a),resultName:b,nextLoc:c};"next"===this.method&&
(this.arg=G);return h}};return y}("object"===("undefined"===typeof module?"undefined":_typeof(module))?module.exports:{});try{_regenerator=B}catch(y){Function("r","_regenerator = r")(B)}})();
(function(){function B(x){var n=null;x==seraph_accel.Gen.hr.E_CONTEXT_EXPIRED?n=E("OpSrvCtxExpired","admin.Manage","seraphinite-accelerator"):seraph_accel.Gen.hr.Fail(x)&&(n=G(E("OpSrvErr_%1$08X","admin.Manage","seraphinite-accelerator"),x));return n}function y(){y=_asyncToGenerator(_regenerator.mark(function r(n){return _regenerator.wrap(function(k){for(;;)switch(k.prev=k.next){case 0:return jQuery(n).attr("disabled",!0),k.prev=1,k.next=4,jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+
"LogClear",{}),type:"POST",data:"",dataType:"json",cache:!1});case 4:k.next=8;break;case 6:k.prev=6,k.t0=k["catch"](1);case 8:jQuery(n).attr("disabled",!1);case 9:case "end":return k.stop()}},r,this,[[1,6]])}));return y.apply(this,arguments)}function K(){K=_asyncToGenerator(_regenerator.mark(function k(n,r){var l,g,v,e,h,f;return _regenerator.wrap(function(q){for(;;)switch(q.prev=q.next){case 0:l=jQuery(n.parentNode).closest(".blck").first();g=l.find(".seraph_accel_spinner");l.find(".content");v=
l.find('input[type="button"]:not(.cancel)');e=l.find('input[type="button"].cancel');if(!r){q.next=23;break}v.prop("disabled",!0);g.show();seraph_accel.Manager._int.notRefreshStat=!0;h=null;q.prev=10;q.next=13;return jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+"UpdateStatBegin",{}),cache:!1,dataType:"json"});case 13:f=q.sent;seraph_accel.Gen.hr.Fail(f)&&(h=G(E("OpSrvErr_%1$08X","admin.Manage","seraphinite-accelerator"),f));q.next=20;break;case 17:q.prev=17,
q.t0=q["catch"](10),h="HTTP "+q.t0.status;case 20:return h&&(alert(h),v.prop("disabled",!1),g.hide()),delete seraph_accel.Manager._int.notRefreshStat,q.abrupt("return");case 23:return e.prop("disabled",!0),seraph_accel.Manager._int.notRefreshStat=!0,h=null,q.prev=26,q.next=29,jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+"UpdateStatCancel",{}),type:"POST",data:"",cache:!1,dataType:"json"});case 29:f=q.sent;h=B(f);q.next=37;break;case 33:q.prev=33,q.t1=q["catch"](26),
h="HTTP "+q.t1.status,e.prop("disabled",!1);case 37:h&&alert(h),delete seraph_accel.Manager._int.notRefreshStat;case 39:case "end":return q.stop()}},k,this,[[10,17],[26,33]])}));return K.apply(this,arguments)}function J(x){switch(x){case 0:return E("OpDescr_Invalidate","admin.Manage","seraphinite-accelerator");case 3:return E("OpDescr_CheckInvalidate","admin.Manage","seraphinite-accelerator");case 2:return E("OpDescr_Delete","admin.Manage","seraphinite-accelerator");case 10:return E("OpDescr_SrvDel",
"admin.Manage","seraphinite-accelerator")}return""+x}function H(){H=_asyncToGenerator(_regenerator.mark(function r(n){var k,l,g,v;return _regenerator.wrap(function(e){for(;;)switch(e.prev=e.next){case 0:return k=jQuery(n.parentNode).closest(".blck").first(),l=k.find('input[type="button"].cancel'),l.prop("disabled",!0),g=null,e.prev=4,e.next=7,jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+"PostUpdCancel",{}),type:"POST",data:"",cache:!1,dataType:"json"});case 7:v=
e.sent;g=B(v);e.next=14;break;case 11:e.prev=11,e.t0=e["catch"](4),g="HTTP "+e.t0.status;case 14:g&&alert(g);case 15:case "end":return e.stop()}},r,this,[[4,11]])}));return H.apply(this,arguments)}function F(){F=_asyncToGenerator(_regenerator.mark(function r(n){var k,l,g,v;return _regenerator.wrap(function(e){for(;;)switch(e.prev=e.next){case 0:return k=jQuery(n.parentNode).closest(".blck").first(),l=k.find('input[type="button"].cancel'),l.prop("disabled",!0),g=null,e.prev=4,e.next=7,jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+
"ScheUpdCancel",{}),type:"POST",data:"",cache:!1,dataType:"json"});case 7:v=e.sent;g=B(v);e.next=14;break;case 11:e.prev=11,e.t0=e["catch"](4),g="HTTP "+e.t0.status;case 14:g&&alert(g);case 15:case "end":return e.stop()}},r,this,[[4,11]])}));return F.apply(this,arguments)}function C(){C=_asyncToGenerator(_regenerator.mark(function r(n){var k,l,g,v,e,h;return _regenerator.wrap(function(f){for(;;)switch(f.prev=f.next){case 0:return k=jQuery(n.parentNode).closest(".blck").first(),l=k.find(".seraph_accel_spinner"),
g=k.find('input[type="button"]:not(.cancel)'),v=k.find('input[type="button"].cancel'),l.show(),g.prop("disabled",!0),v.prop("disabled",!1),seraph_accel.Manager._int.notRefreshExtDp=!0,e=null,f.prev=9,f.next=12,jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+"ExtDbUpdBegin",{}),type:"POST",data:"",cache:!1,dataType:"json"});case 12:h=f.sent;e=B(h);f.next=19;break;case 16:f.prev=16,f.t0=f["catch"](9),e="HTTP "+f.t0.status;case 19:e&&alert(e),delete seraph_accel.Manager._int.notRefreshExtDp;
case 21:case "end":return f.stop()}},r,this,[[9,16]])}));return C.apply(this,arguments)}function I(){I=_asyncToGenerator(_regenerator.mark(function r(n){var k,l,g,v;return _regenerator.wrap(function(e){for(;;)switch(e.prev=e.next){case 0:return k=jQuery(n.parentNode).closest(".blck").first(),l=k.find('input[type="button"].cancel'),l.prop("disabled",!0),g=null,e.prev=4,e.next=7,jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+"ExtDbUpdCancel",{}),type:"POST",data:"",
cache:!1,dataType:"json"});case 7:v=e.sent;g=B(v);e.next=14;break;case 11:e.prev=11,e.t0=e["catch"](4),g="HTTP "+e.t0.status;case 14:g&&alert(g);case 15:case "end":return e.stop()}},r,this,[[4,11]])}));return I.apply(this,arguments)}function D(){D=_asyncToGenerator(_regenerator.mark(function l(n,r,k){var g,v,e,h,f,q,a,b,c,m,d,p,t,w,u,A;return _regenerator.wrap(function(z){for(;;)switch(z.prev=z.next){case 0:return g=jQuery(n.parentNode).closest(".blck").first(),v=g.find(".seraph_accel_spinner"),e=
g.find(".descr"),h=g.find('input[type="button"]:not(.cancel)'),f=g.find('input[type="button"].cancel'),q=g.find("#seraph_accel_views"),a=g.find("#seraph_accel_geos"),b=g.find("#seraph_accel_langs"),c=[],q.get()&&(seraph_accel.Ui.TokensMetaTree.Apply(q.get()),c=seraph_accel.Ui.TokensList.GetVal(q.get())),m=[],a.get()&&(seraph_accel.Ui.TokensMetaTree.Apply(a.get()),m=seraph_accel.Ui.TokensList.GetVal(a.get()).filter(function(T){return"_"!==T})),d=[],b.get()&&(seraph_accel.Ui.TokensMetaTree.Apply(b.get()),
d=seraph_accel.Ui.TokensList.GetVal(b.get())),t=String(g.find(".type").val()),"uri"===t?p=g.find(".uri").val():0===t.indexOf("uri:")&&(p=t.substr(4),t="uri"),p="string"==typeof p?seraph_accel.Gen.StrReplaceAll(p,["\r","\n","*"],["",";","{ASTRSK}"]):"",v.show(),e.show(),e.text(J(r)),h.prop("disabled",!0),f.prop("disabled",!1),seraph_accel.Manager._int.notRefreshOp=!0,w={cache:!1,dataType:"json"},512>p.length?w.url=seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+"CacheOpBegin",
{type:t,op:r,uri:p,v:c.join(),g:m.length?m.join():void 0,l:d.length?d.join():void 0,_wpnonce:k}):(w.url=seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+"CacheOpBegin",{type:t,op:r,v:c.join(),g:m.length?m.join():void 0,l:d.length?d.join():void 0,_wpnonce:k}),w.type="POST",w.contentType="application/x-www-form-urlencoded",w.data="uri="+encodeURIComponent(p)),u=null,z.prev=26,z.next=29,jQuery.ajax(w);case 29:A=z.sent;u=B(A);z.next=36;break;case 33:z.prev=33,z.t0=z["catch"](26),
u="HTTP "+z.t0.status;case 36:u&&alert(u),delete seraph_accel.Manager._int.notRefreshOp;case 38:case "end":return z.stop()}},l,this,[[26,33]])}));return D.apply(this,arguments)}function L(){L=_asyncToGenerator(_regenerator.mark(function l(n,r,k){var g,v,e,h;return _regenerator.wrap(function(f){for(;;)switch(f.prev=f.next){case 0:return g=jQuery(n.parentNode).closest(".blck").first(),v=g.find('input[type="button"].cancel'),v.prop("disabled",!0),e=null,f.prev=4,f.next=7,jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+
"CacheOpCancel",{op:r,_wpnonce:k}),type:"POST",data:"",cache:!1,dataType:"json"});case 7:h=f.sent;e=B(h);f.next=14;break;case 11:f.prev=11,f.t0=f["catch"](4),e="HTTP "+f.t0.status;case 14:e&&alert(e);case 15:case "end":return f.stop()}},l,this,[[4,11]])}));return L.apply(this,arguments)}function Q(){Q=_asyncToGenerator(_regenerator.mark(function l(n,r,k){return _regenerator.wrap(function(g){for(;;)switch(g.prev=g.next){case 0:case "end":return g.stop()}},l,this)}));return Q.apply(this,arguments)}
function R(){R=_asyncToGenerator(_regenerator.mark(function l(n,r,k){return _regenerator.wrap(function(g){for(;;)switch(g.prev=g.next){case 0:case "end":return g.stop()}},l,this)}));return R.apply(this,arguments)}function N(){N=_asyncToGenerator(_regenerator.mark(function l(n,r,k){return _regenerator.wrap(function(g){for(;;)switch(g.prev=g.next){case 0:case "end":return g.stop()}},l,this)}));return N.apply(this,arguments)}function M(){M=_asyncToGenerator(_regenerator.mark(function k(n,r){var l,g,
v,e;return _regenerator.wrap(function(h){for(;;)switch(h.prev=h.next){case 0:e=function(){e=_asyncToGenerator(_regenerator.mark(function q(){return _regenerator.wrap(function(a){for(;;)switch(a.prev=a.next){case 0:return a.next=2,seraph_accel.Manager._int.OnDataRefresh(n,r);case 2:g();case 3:case "end":return a.stop()}},q,this)}));return e.apply(this,arguments)},v=function(){return e.apply(this,arguments)},g=function(){var f=1E3*parseInt(l.val(),10);100>f&&(f=100);clearTimeout(seraph_accel.Manager._int.refreshTimer);
seraph_accel.Manager._int.refreshTimer=setTimeout(v,f)},l=jQuery(n).find("#operate .tmDataRefresh"),l.on("change",g),v();case 6:case "end":return h.stop()}},k,this)}));return M.apply(this,arguments)}function O(){O=_asyncToGenerator(_regenerator.mark(function k(n,r){var l,g,v,e,h,f,q,a,b,c,m,d,p,t,w,u,A;return _regenerator.wrap(function(z){for(;;)switch(z.prev=z.next){case 0:return l=jQuery(n).find("#status").first(),g=jQuery(n).find("#stat").first(),v=g.find(".seraph_accel_spinner"),e=g.find('input[type="button"]:not(.cancel)'),
h=g.find('input[type="button"].cancel'),f=jQuery(n).find("#operate").first(),q=f.find(".seraph_accel_spinner"),a=f.find(".descr"),b=f.find('input[type="button"]:not(.cancel)'),c=f.find('input[type="button"].cancel'),m=jQuery(n).find("#queue").first(),m.find(".content"),d=m.find(".maxItems"),m.find(".seraph_accel_spinner"),m.find('input[type="button"]'),m.find(".descrNums"),z.prev=16,z.next=19,jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+"GetData",{nMaxQueueItems:d.val(),
allSites:r?!0:void 0}),type:"GET",cache:!1,dataType:"json"});case 19:u=z.sent;z.next=24;break;case 22:z.prev=22,z.t0=z["catch"](16);case 24:if(u){z.next=26;break}return z.abrupt("return");case 26:if(!r){for(A in u.status.cont)l.find('[data-id-cont="'+A+'"]').html(u.status.cont[A]);seraph_accel.Manager._int.notRefreshPostUpd||(p=l.find(".blck.postupd .seraph_accel_spinner"),t=l.find('.blck.postupd input[type="button"]:not(.cancel)'),w=l.find('.blck.postupd input[type="button"].cancel'),u.status.postUpd?
(p.show(),t.prop("disabled",!0),w.prop("disabled",!1)):(p.hide(),t.prop("disabled",!1),w.prop("disabled",!0)));seraph_accel.Manager._int.notRefreshScheUpd||(p=l.find(".blck.scheupd .seraph_accel_spinner"),t=l.find('.blck.scheupd input[type="button"]:not(.cancel)'),w=l.find('.blck.scheupd input[type="button"].cancel'),u.status.scheUpd?(p.show(),t.prop("disabled",!0),w.prop("disabled",!1)):(p.hide(),t.prop("disabled",!1),w.prop("disabled",!0)));seraph_accel.Manager._int.notRefreshCleanup||(p=l.find(".blck.cleanup .seraph_accel_spinner"),
t=l.find('.blck.cleanup input[type="button"]:not(.cancel)'),w=l.find('.blck.cleanup input[type="button"].cancel'),u.status.cleanUp?(p.show(),t.prop("disabled",!0),w.prop("disabled",!1)):(p.hide(),t.prop("disabled",!1),w.prop("disabled",!0)))}r||seraph_accel.Manager._int.notRefreshExtDp||(p=l.find(".blck.extdb .seraph_accel_spinner"),t=l.find('.blck.extdb input[type="button"]:not(.cancel)'),w=l.find('.blck.extdb input[type="button"].cancel'),u.extDb.isUpdating?(p.show(),t.prop("disabled",!0),w.prop("disabled",
!1)):(p.hide(),t.prop("disabled",!1),w.prop("disabled",!0)));r||seraph_accel.Manager._int.notRefreshStat||(u.stat.isUpdating?(v.show(),e.prop("disabled",!0),h.prop("disabled",!1)):(v.hide(),e.prop("disabled",!1),h.prop("disabled",!0)),g.find('[data-id-cont="stat"]').html(u.stat.cont));r||seraph_accel.Manager._int.notRefreshOp||(null===u.curOp&&(u.curOp=void 0),void 0!==u.curOp?(q.show(),a.show(),a.text(J(u.curOp)),b.prop("disabled",!0),c.prop("disabled",!1)):(q.hide(),a.hide(),b.prop("disabled",!1),
c.prop("disabled",!0),a.text("")));case 30:case "end":return z.stop()}},k,this,[[16,22]])}));return O.apply(this,arguments)}function P(){P=_asyncToGenerator(_regenerator.mark(function r(n){var k,l,g,v,e,h,f,q;return _regenerator.wrap(function(a){for(;;)switch(a.prev=a.next){case 0:return k=jQuery(n.parentNode).closest(".blck").first(),l=k.find(".url"),g=k.find(".messages"),v=k.find(".seraph_accel_spinner"),e=k.find('input[type="button"]'),h=0,k.find(".liteChk").prop("checked")&&(h|=1),k.find(".medChk").prop("checked")&&
(h|=2),k.find(".tidyChk").prop("checked")&&(h|=524288),g.empty(),v.show(),e.prop("disabled",!0),a.prev=12,a.next=15,jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+"HtmlCheck",{url:l.val(),norm:h}),type:"POST",data:"",dataType:"json",cache:!1});case 15:f=a.sent;a.next=21;break;case 18:a.prev=18,a.t0=a["catch"](12),f={err:a.t0.statusText};case 21:v.hide();e.prop("disabled",!1);if(!f.err){a.next=26;break}g.append(seraph_accel.Ui.LogItem("error",f.err));return a.abrupt("return");
case 26:for(q in f.list)q=f.list[q],g.append(seraph_accel.Ui.LogItem(q.severity,q.text));case 27:case "end":return a.stop()}},r,this,[[12,18]])}));return P.apply(this,arguments)}var S=seraph_accel.Wp.Loc.GetApi(),E=S._x,G=S.sprintf;seraph_accel.Settings={_int:{OnUpdateCssAuto:function(x){seraph_accel.Ui.ComboShowDependedItems(x,jQuery(x.parentNode).closest(".blck").first().get(0))},OnLogClear:function(x){return y.apply(this,arguments)}}};seraph_accel.Manager={_int:{OnStatOp:function(x,n){return K.apply(this,
arguments)},OnCacheOp:function(x,n,r){return D.apply(this,arguments)},OnCacheOpCancel:function(x,n,r){return L.apply(this,arguments)},OnPostUpdCancel:function(x){return H.apply(this,arguments)},OnScheUpdCancel:function(x){return F.apply(this,arguments)},OnExtDbUpdBegin:function(x){return C.apply(this,arguments)},OnExtDbUpdCancel:function(x){return I.apply(this,arguments)},OnQueueDel:function(x,n,r){return Q.apply(this,arguments)},OnQueuePause:function(x,n,r){return R.apply(this,arguments)},OnQueueItemCancel:function(x,
n,r){return N.apply(this,arguments)},OnDataRefreshInit:function(x,n){return M.apply(this,arguments)},OnDataRefresh:function(x,n){return O.apply(this,arguments)},OnHtmlCheck:function(x){return P.apply(this,arguments)}}};(function(){function x(l){return n.apply(this,arguments)}function n(){n=_asyncToGenerator(_regenerator.mark(function v(g){var e,h;return _regenerator.wrap(function(f){for(;;)switch(f.prev=f.next){case 0:return e={},f.prev=1,seraph_accel.SelfDiag._int.curAjax=jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+
"SelfDiag_"+g,{}),cache:!1,dataType:"json"}),f.next=5,seraph_accel.SelfDiag._int.curAjax;case 5:e=f.sent;delete seraph_accel.SelfDiag._int.curAjax;f.next=14;break;case 9:f.prev=9,f.t0=f["catch"](1),delete seraph_accel.SelfDiag._int.curAjax,0===f.t0.status?e.hr=seraph_accel.Gen.hr.S_ABORTED:(e.hr=seraph_accel.Gen.hr.E_FAIL,e.descr="HTTP "+f.t0.status),500==f.t0.status&&(h=document.implementation.createHTMLDocument(""),h.documentElement.innerHTML=f.t0.responseText,h=h.body.textContent,h=seraph_accel.Gen.StrReplaceAll(h,
"\r",""),h=seraph_accel.Gen.StrReplaceAll(h,["\t","\v"]," "),h=seraph_accel.Gen.StrReplaceAll(h,"\n",". "),(h=seraph_accel.Gen.StrReplaceAllWhileChanging(h,["  ",". . "],[" ",". "]).trim())&&"."!=h&&(e.descr+="<br>"+h));case 14:return f.abrupt("return",e);case 15:case "end":return f.stop()}},v,this,[[1,9]])}));return n.apply(this,arguments)}function r(){r=_asyncToGenerator(_regenerator.mark(function v(g){var e,h,f,q,a,b,c,m,d,p,t,w=arguments;return _regenerator.wrap(function(u){for(;;)switch(u.prev=
u.next){case 0:e=1<w.length&&void 0!==w[1]?w[1]:!1;h=jQuery(g.parentNode).closest(".blck").first();f=h.find(".seraph_accel_spinner");q=h.find('input[type="button"]:not(.cancel)');a=h.find('input[type="button"].cancel');b=h.find(".log");c=[{id:"3rdPartySettCompat",name:k("TestName_3rdPartySettCompat","admin.SelfDiag","seraphinite-accelerator")},{id:"AsyncRequest",name:k("TestName_AsyncRequest","admin.SelfDiag","seraphinite-accelerator")},{id:"SetMaxExecTime",name:k("TestName_SetMaxExecTime","admin.SelfDiag",
"seraphinite-accelerator")},{id:"PageOptimize",name:k("TestName_PageOptimize","admin.SelfDiag","seraphinite-accelerator")},{id:"VendorSrv",name:k("TestName_VendorSrv","admin.SelfDiag","seraphinite-accelerator")},{id:"ExtCache",name:k("TestName_ExtCache","admin.SelfDiag","seraphinite-accelerator")}];b.empty();for(m=0;m<c.length;m++)d=c[m],b.append(seraph_accel.Ui.LogItem("none",seraph_accel.Ui.Tag("strong",d.name?d.name:d.id),!1));if(!e){u.next=11;break}return u.abrupt("return");case 11:f.show(),q.prop("disabled",
!0),a.prop("disabled",!1),seraph_accel.SelfDiag._int.inProgress=!0,m=0;case 16:if(!(m<c.length)){u.next=31;break}d=c[m];jQuery(b.children().get(m)).replaceWith(seraph_accel.Ui.LogItem("info",seraph_accel.Ui.Tag("strong",d.name?d.name:d.id)+k("TestRunning","admin.SelfDiag","seraphinite-accelerator"),!1));u.next=21;return x(d.id);case 21:p=u.sent;t=k("TestSucc","admin.SelfDiag","seraphinite-accelerator");p.hr!=seraph_accel.Gen.hr.S_OK&&(t=seraph_accel.Gen.hr.Succ(p.hr)?p.hr==seraph_accel.Gen.hr.S_ABORTED?
k("TestAbort","admin.SelfDiag","seraphinite-accelerator"):p.hr==seraph_accel.Gen.hr.S_FALSE?k("TestNotice","admin.SelfDiag","seraphinite-accelerator"):k("TestWarn","admin.SelfDiag","seraphinite-accelerator"):k("TestError","admin.SelfDiag","seraphinite-accelerator"));p.descr&&(t+="<br>"+p.descr);jQuery(b.children().get(m)).replaceWith(seraph_accel.Ui.LogItem(p.hr==seraph_accel.Gen.hr.S_OK?"success":seraph_accel.Gen.hr.Succ(p.hr)?p.hr==seraph_accel.Gen.hr.S_FALSE?"normal":"warning":"error",seraph_accel.Ui.Tag("strong",
d.name?d.name:d.id)+t,!1));if(seraph_accel.SelfDiag._int.inProgress){u.next=28;break}return u.abrupt("break",31);case 28:m++;u.next=16;break;case 31:f.hide(),q.prop("disabled",!1),a.prop("disabled",!0);case 34:case "end":return u.stop()}},v,this)}));return r.apply(this,arguments)}var k=seraph_accel.Wp.Loc.GetApi()._x;seraph_accel.SelfDiag={_int:{OnStart:function(l){return r.apply(this,arguments)},OnCancel:function(l){l=jQuery(l.parentNode).closest(".blck").first();l.find(".seraph_accel_spinner");
l.find('input[type="button"]:not(.cancel)');l.find('input[type="button"].cancel').prop("disabled",!0);seraph_accel.SelfDiag._int.inProgress=!1;seraph_accel.SelfDiag._int.curAjax&&seraph_accel.SelfDiag._int.curAjax.abort()},inProgress:!1}}})()})();
