function asyncGeneratorStep(E,w,J,F,G,D,A){try{var H=E[D](A),B=H.value}catch(K){J(K);return}H.done?w(B):Promise.resolve(B).then(F,G)}function _asyncToGenerator(E){return function(){var w=this,J=arguments;return new Promise(function(F,G){function D(B){asyncGeneratorStep(H,F,G,D,A,"next",B)}function A(B){asyncGeneratorStep(H,F,G,D,A,"throw",B)}var H=E.apply(w,J);D(void 0)})}}
function _typeof(E){_typeof="function"===typeof Symbol&&"symbol"===typeof Symbol.iterator?function(w){return typeof w}:function(w){return w&&"function"===typeof Symbol&&w.constructor===Symbol&&w!==Symbol.prototype?"symbol":typeof w};return _typeof(E)}var _regenerator;
(function(){var E=function(w){function J(b,a,c,m){a=Object.create((a&&a.prototype instanceof G?a:G).prototype);m=new L(m||[]);a._invoke=K(b,c,m);return a}function F(b,a,c){try{return{type:"normal",arg:b.call(a,c)}}catch(m){return{type:"throw",arg:m}}}function G(){}function D(){}function A(){}function H(b){["next","throw","return"].forEach(function(a){b[a]=function(c){return this._invoke(a,c)}})}function B(b,a){function c(d,x,u,y){d=F(b[d],b,x);if("throw"===d.type)y(d.arg);else{var M=d.arg;return(d=
M.value)&&"object"===_typeof(d)&&z.call(d,"__await")?a.resolve(d.__await).then(function(I){c("next",I,u,y)},function(I){c("throw",I,u,y)}):a.resolve(d).then(function(I){M.value=I;u(M)},function(I){return c("throw",I,u,y)})}}var m;this._invoke=function(d,x){function u(){return new a(function(y,M){c(d,x,y,M)})}return m=m?m.then(u,u):u()}}function K(b,a,c){var m=l;return function(d,x){if(m===e)throw Error("Generator is already running");if(m===k){if("throw"===d)throw x;return Q()}c.method=d;for(c.arg=
x;;){if(d=c.delegate)if(d=P(d,c)){if(d===g)continue;return d}if("next"===c.method)c.sent=c._sent=c.arg;else if("throw"===c.method){if(m===l)throw m=k,c.arg;c.dispatchException(c.arg)}else"return"===c.method&&c.abrupt("return",c.arg);m=e;d=F(b,a,c);if("normal"===d.type){m=c.done?k:r;if(d.arg===g)continue;return{value:d.arg,done:c.done}}"throw"===d.type&&(m=k,c.method="throw",c.arg=d.arg)}}}function P(b,a){var c=b.iterator[a.method];if(c===t){a.delegate=null;if("throw"===a.method){if(b.iterator["return"]&&
(a.method="return",a.arg=t,P(b,a),"throw"===a.method))return g;a.method="throw";a.arg=new TypeError("The iterator does not provide a 'throw' method")}return g}c=F(c,b.iterator,a.arg);if("throw"===c.type)return a.method="throw",a.arg=c.arg,a.delegate=null,g;c=c.arg;if(!c)return a.method="throw",a.arg=new TypeError("iterator result is not an object"),a.delegate=null,g;if(c.done)a[b.resultName]=c.value,a.next=b.nextLoc,"return"!==a.method&&(a.method="next",a.arg=t);else return c;a.delegate=null;return g}
function R(b){var a={tryLoc:b[0]};1 in b&&(a.catchLoc=b[1]);2 in b&&(a.finallyLoc=b[2],a.afterLoc=b[3]);this.tryEntries.push(a)}function N(b){var a=b.completion||{};a.type="normal";delete a.arg;b.completion=a}function L(b){this.tryEntries=[{tryLoc:"root"}];b.forEach(R,this);this.reset(!0)}function O(b){if(b){var a=b[q];if(a)return a.call(b);if("function"===typeof b.next)return b;if(!isNaN(b.length)){var c=-1;a=function d(){for(;++c<b.length;)if(z.call(b,c))return d.value=b[c],d.done=!1,d;d.value=
t;d.done=!0;return d};return a.next=a}}return{next:Q}}function Q(){return{value:t,done:!0}}var C=Object.prototype,z=C.hasOwnProperty,t,n="function"===typeof Symbol?Symbol:{},q=n.iterator||"@@iterator",f=n.asyncIterator||"@@asyncIterator",h=n.toStringTag||"@@toStringTag";w.wrap=J;var l="suspendedStart",r="suspendedYield",e="executing",k="completed",g={};n={};n[q]=function(){return this};var p=Object.getPrototypeOf;(p=p&&p(p(O([]))))&&p!==C&&z.call(p,q)&&(n=p);var v=A.prototype=G.prototype=Object.create(n);
D.prototype=v.constructor=A;A.constructor=D;A[h]=D.displayName="GeneratorFunction";w.isGeneratorFunction=function(b){return(b="function"===typeof b&&b.constructor)?b===D||"GeneratorFunction"===(b.displayName||b.name):!1};w.mark=function(b){Object.setPrototypeOf?Object.setPrototypeOf(b,A):(b.__proto__=A,h in b||(b[h]="GeneratorFunction"));b.prototype=Object.create(v);return b};w.awrap=function(b){return{__await:b}};H(B.prototype);B.prototype[f]=function(){return this};w.AsyncIterator=B;w.async=function(b,
a,c,m,d){void 0===d&&(d=Promise);var x=new B(J(b,a,c,m),d);return w.isGeneratorFunction(a)?x:x.next().then(function(u){return u.done?u.value:x.next()})};H(v);v[h]="Generator";v[q]=function(){return this};v.toString=function(){return"[object Generator]"};w.keys=function(b){var a=[],c;for(c in b)a.push(c);a.reverse();return function d(){for(;a.length;){var x=a.pop();if(x in b)return d.value=x,d.done=!1,d}d.done=!0;return d}};w.values=O;L.prototype={constructor:L,reset:function(b){this.next=this.prev=
0;this.sent=this._sent=t;this.done=!1;this.delegate=null;this.method="next";this.arg=t;this.tryEntries.forEach(N);if(!b)for(var a in this)"t"===a.charAt(0)&&z.call(this,a)&&!isNaN(+a.slice(1))&&(this[a]=t)},stop:function(){this.done=!0;var b=this.tryEntries[0].completion;if("throw"===b.type)throw b.arg;return this.rval},dispatchException:function(b){function a(M,I){x.type="throw";x.arg=b;c.next=M;I&&(c.method="next",c.arg=t);return!!I}if(this.done)throw b;for(var c=this,m=this.tryEntries.length-1;0<=
m;--m){var d=this.tryEntries[m],x=d.completion;if("root"===d.tryLoc)return a("end");if(d.tryLoc<=this.prev){var u=z.call(d,"catchLoc"),y=z.call(d,"finallyLoc");if(u&&y){if(this.prev<d.catchLoc)return a(d.catchLoc,!0);if(this.prev<d.finallyLoc)return a(d.finallyLoc)}else if(u){if(this.prev<d.catchLoc)return a(d.catchLoc,!0)}else if(y){if(this.prev<d.finallyLoc)return a(d.finallyLoc)}else throw Error("try statement without catch or finally");}}},abrupt:function(b,a){for(var c=this.tryEntries.length-
1;0<=c;--c){var m=this.tryEntries[c];if(m.tryLoc<=this.prev&&z.call(m,"finallyLoc")&&this.prev<m.finallyLoc){var d=m;break}}d&&("break"===b||"continue"===b)&&d.tryLoc<=a&&a<=d.finallyLoc&&(d=null);c=d?d.completion:{};c.type=b;c.arg=a;return d?(this.method="next",this.next=d.finallyLoc,g):this.complete(c)},complete:function(b,a){if("throw"===b.type)throw b.arg;"break"===b.type||"continue"===b.type?this.next=b.arg:"return"===b.type?(this.rval=this.arg=b.arg,this.method="return",this.next="end"):"normal"===
b.type&&a&&(this.next=a);return g},finish:function(b){for(var a=this.tryEntries.length-1;0<=a;--a){var c=this.tryEntries[a];if(c.finallyLoc===b)return this.complete(c.completion,c.afterLoc),N(c),g}},"catch":function(b){for(var a=this.tryEntries.length-1;0<=a;--a){var c=this.tryEntries[a];if(c.tryLoc===b){b=c.completion;if("throw"===b.type){var m=b.arg;N(c)}return m}}throw Error("illegal catch attempt");},delegateYield:function(b,a,c){this.delegate={iterator:O(b),resultName:a,nextLoc:c};"next"===this.method&&
(this.arg=t);return g}};return w}("object"===("undefined"===typeof module?"undefined":_typeof(module))?module.exports:{});try{_regenerator=E}catch(w){Function("r","_regenerator = r")(E)}})();
(function(){function E(){E=_asyncToGenerator(_regenerator.mark(function q(n){return _regenerator.wrap(function(f){for(;;)switch(f.prev=f.next){case 0:return jQuery(n).attr("disabled",!0),f.prev=1,f.next=4,jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+"LogClear",{}),type:"POST",data:"",dataType:"json",cache:!1});case 4:f.next=8;break;case 6:f.prev=6,f.t0=f["catch"](1);case 8:jQuery(n).attr("disabled",!1);case 9:case "end":return f.stop()}},q,this,[[1,6]])}));
return E.apply(this,arguments)}function w(){w=_asyncToGenerator(_regenerator.mark(function f(n,q){var h,l,r,e,k,g;return _regenerator.wrap(function(p){for(;;)switch(p.prev=p.next){case 0:h=jQuery(n.parentNode).closest(".blck").first();l=h.find(".seraph_accel_spinner");h.find(".content");r=h.find('input[type="button"]:not(.cancel)');e=h.find('input[type="button"].cancel');if(!q){p.next=23;break}r.prop("disabled",!0);l.show();seraph_accel.Manager._int.notRefreshStat=!0;k=null;p.prev=10;p.next=13;return jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+
"UpdateStatBegin",{}),cache:!1,dataType:"json"});case 13:g=p.sent;seraph_accel.Gen.hr.Fail(g)&&(k=z(C("OpSrvErr_%1$08X","admin.Manage","seraphinite-accelerator"),g));p.next=20;break;case 17:p.prev=17,p.t0=p["catch"](10),k="HTTP "+p.t0.status;case 20:return k&&(alert(k),r.prop("disabled",!1),l.hide()),delete seraph_accel.Manager._int.notRefreshStat,p.abrupt("return");case 23:return e.prop("disabled",!0),seraph_accel.Manager._int.notRefreshStat=!0,k=null,p.prev=26,p.next=29,jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+
"UpdateStatCancel",{}),type:"POST",data:"",cache:!1,dataType:"json"});case 29:g=p.sent;seraph_accel.Gen.hr.Fail(g)&&(k=z(C("OpSrvErr_%1$08X","admin.Manage","seraphinite-accelerator"),g));p.next=37;break;case 33:p.prev=33,p.t1=p["catch"](26),k="HTTP "+p.t1.status,e.prop("disabled",!1);case 37:k&&alert(k),delete seraph_accel.Manager._int.notRefreshStat;case 39:case "end":return p.stop()}},f,this,[[10,17],[26,33]])}));return w.apply(this,arguments)}function J(t){switch(t){case 0:return C("OpDescr_Invalidate",
"admin.Manage","seraphinite-accelerator");case 3:return C("OpDescr_CheckInvalidate","admin.Manage","seraphinite-accelerator");case 2:return C("OpDescr_Delete","admin.Manage","seraphinite-accelerator");case 10:return C("OpDescr_SrvDel","admin.Manage","seraphinite-accelerator")}return""+t}function F(){F=_asyncToGenerator(_regenerator.mark(function q(n){var f,h,l,r;return _regenerator.wrap(function(e){for(;;)switch(e.prev=e.next){case 0:return f=jQuery(n.parentNode).closest(".blck").first(),h=f.find('input[type="button"].cancel'),
h.prop("disabled",!0),l=null,e.prev=4,e.next=7,jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+"PostUpdCancel",{}),type:"POST",data:"",cache:!1,dataType:"json"});case 7:r=e.sent;seraph_accel.Gen.hr.Fail(r)&&(l=z(C("OpSrvErr_%1$08X","admin.Manage","seraphinite-accelerator"),r));e.next=14;break;case 11:e.prev=11,e.t0=e["catch"](4),l="HTTP "+e.t0.status;case 14:l&&alert(l);case 15:case "end":return e.stop()}},q,this,[[4,11]])}));return F.apply(this,arguments)}function G(){G=
_asyncToGenerator(_regenerator.mark(function q(n){var f,h,l,r;return _regenerator.wrap(function(e){for(;;)switch(e.prev=e.next){case 0:return f=jQuery(n.parentNode).closest(".blck").first(),h=f.find('input[type="button"].cancel'),h.prop("disabled",!0),l=null,e.prev=4,e.next=7,jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+"ScheUpdCancel",{}),type:"POST",data:"",cache:!1,dataType:"json"});case 7:r=e.sent;seraph_accel.Gen.hr.Fail(r)&&(l=z(C("OpSrvErr_%1$08X",
"admin.Manage","seraphinite-accelerator"),r));e.next=14;break;case 11:e.prev=11,e.t0=e["catch"](4),l="HTTP "+e.t0.status;case 14:l&&alert(l);case 15:case "end":return e.stop()}},q,this,[[4,11]])}));return G.apply(this,arguments)}function D(){D=_asyncToGenerator(_regenerator.mark(function q(n){var f,h,l,r,e,k;return _regenerator.wrap(function(g){for(;;)switch(g.prev=g.next){case 0:return f=jQuery(n.parentNode).closest(".blck").first(),h=f.find(".seraph_accel_spinner"),l=f.find('input[type="button"]:not(.cancel)'),
r=f.find('input[type="button"].cancel'),h.show(),l.prop("disabled",!0),r.prop("disabled",!1),seraph_accel.Manager._int.notRefreshExtDp=!0,e=null,g.prev=9,g.next=12,jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+"ExtDbUpdBegin",{}),type:"POST",data:"",cache:!1,dataType:"json"});case 12:k=g.sent;seraph_accel.Gen.hr.Fail(k)&&(e=z(C("OpSrvErr_%1$08X","admin.Manage","seraphinite-accelerator"),k));g.next=19;break;case 16:g.prev=16,g.t0=g["catch"](9),e="HTTP "+g.t0.status;
case 19:e&&alert(e),delete seraph_accel.Manager._int.notRefreshExtDp;case 21:case "end":return g.stop()}},q,this,[[9,16]])}));return D.apply(this,arguments)}function A(){A=_asyncToGenerator(_regenerator.mark(function q(n){var f,h,l,r;return _regenerator.wrap(function(e){for(;;)switch(e.prev=e.next){case 0:return f=jQuery(n.parentNode).closest(".blck").first(),h=f.find('input[type="button"].cancel'),h.prop("disabled",!0),l=null,e.prev=4,e.next=7,jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+
"ExtDbUpdCancel",{}),type:"POST",data:"",cache:!1,dataType:"json"});case 7:r=e.sent;seraph_accel.Gen.hr.Fail(r)&&(l=z(C("OpSrvErr_%1$08X","admin.Manage","seraphinite-accelerator"),r));e.next=14;break;case 11:e.prev=11,e.t0=e["catch"](4),l="HTTP "+e.t0.status;case 14:l&&alert(l);case 15:case "end":return e.stop()}},q,this,[[4,11]])}));return A.apply(this,arguments)}function H(){H=_asyncToGenerator(_regenerator.mark(function f(n,q){var h,l,r,e,k,g,p,v,b,a,c,m,d,x;return _regenerator.wrap(function(u){for(;;)switch(u.prev=
u.next){case 0:return h=jQuery(n.parentNode).closest(".blck").first(),l=h.find(".seraph_accel_spinner"),r=h.find(".descr"),e=h.find('input[type="button"]:not(.cancel)'),k=h.find('input[type="button"].cancel'),g=h.find("#seraph_accel_views"),p=h.find("#seraph_accel_geos"),v=[],g.get()&&(seraph_accel.Ui.TokensMetaTree.Apply(g.get()),v=seraph_accel.Ui.TokensList.GetVal(g.get())),b=[],p.get()&&(seraph_accel.Ui.TokensMetaTree.Apply(p.get()),b=seraph_accel.Ui.TokensList.GetVal(p.get())),c=String(h.find(".type").val()),
"uri"===c?a=h.find(".uri").val():0===c.indexOf("uri:")&&(a=c.substr(4),c="uri"),a=seraph_accel.Gen.StrReplaceAll(String(a),["\r","\n","*"],["",";","{ASTRSK}"]),l.show(),r.show(),r.text(J(q)),e.prop("disabled",!0),k.prop("disabled",!1),seraph_accel.Manager._int.notRefreshOp=!0,m={cache:!1,dataType:"json"},512>a.length?m.url=seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+"CacheOpBegin",{type:c,op:q,uri:a,v:v.join(),g:b.length?b.join():void 0}):(m.url=seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+
"CacheOpBegin",{type:c,op:q,v:v.join(),g:b.length?b.join():void 0}),m.type="POST",m.contentType="application/x-www-form-urlencoded",m.data="uri="+encodeURIComponent(a)),d=null,u.prev=23,u.next=26,jQuery.ajax(m);case 26:x=u.sent;seraph_accel.Gen.hr.Fail(x)&&(d=z(C("OpSrvErr_%1$08X","admin.Manage","seraphinite-accelerator"),x));u.next=33;break;case 30:u.prev=30,u.t0=u["catch"](23),d="HTTP "+u.t0.status;case 33:d&&alert(d),delete seraph_accel.Manager._int.notRefreshOp;case 35:case "end":return u.stop()}},
f,this,[[23,30]])}));return H.apply(this,arguments)}function B(){B=_asyncToGenerator(_regenerator.mark(function f(n,q){var h,l,r,e;return _regenerator.wrap(function(k){for(;;)switch(k.prev=k.next){case 0:return h=jQuery(n.parentNode).closest(".blck").first(),l=h.find('input[type="button"].cancel'),l.prop("disabled",!0),r=null,k.prev=4,k.next=7,jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+"CacheOpCancel",{op:q}),type:"POST",data:"",cache:!1,dataType:"json"});
case 7:e=k.sent;seraph_accel.Gen.hr.Fail(e)&&(r=z(C("OpSrvErr_%1$08X","admin.Manage","seraphinite-accelerator"),e));k.next=14;break;case 11:k.prev=11,k.t0=k["catch"](4),r="HTTP "+k.t0.status;case 14:r&&alert(r);case 15:case "end":return k.stop()}},f,this,[[4,11]])}));return B.apply(this,arguments)}function K(){K=_asyncToGenerator(_regenerator.mark(function h(n,q,f){return _regenerator.wrap(function(l){for(;;)switch(l.prev=l.next){case 0:case "end":return l.stop()}},h,this)}));return K.apply(this,
arguments)}function P(){P=_asyncToGenerator(_regenerator.mark(function h(n,q,f){return _regenerator.wrap(function(l){for(;;)switch(l.prev=l.next){case 0:case "end":return l.stop()}},h,this)}));return P.apply(this,arguments)}function R(){R=_asyncToGenerator(_regenerator.mark(function h(n,q,f){return _regenerator.wrap(function(l){for(;;)switch(l.prev=l.next){case 0:case "end":return l.stop()}},h,this)}));return R.apply(this,arguments)}function N(){N=_asyncToGenerator(_regenerator.mark(function f(n,
q){return _regenerator.wrap(function(h){for(;;)switch(h.prev=h.next){case 0:case "end":return h.stop()}},f,this)}));return N.apply(this,arguments)}function L(){L=_asyncToGenerator(_regenerator.mark(function f(n,q){return _regenerator.wrap(function(h){for(;;)switch(h.prev=h.next){case 0:case "end":return h.stop()}},f,this)}));return L.apply(this,arguments)}function O(){O=_asyncToGenerator(_regenerator.mark(function q(n){var f,h,l,r,e,k,g,p;return _regenerator.wrap(function(v){for(;;)switch(v.prev=
v.next){case 0:return f=jQuery(n.parentNode).closest(".blck").first(),h=f.find(".url"),l=f.find(".messages"),r=f.find(".seraph_accel_spinner"),e=f.find('input[type="button"]'),k=0,f.find(".liteChk").prop("checked")&&(k|=1),f.find(".medChk").prop("checked")&&(k|=2),f.find(".tidyChk").prop("checked")&&(k|=524288),l.empty(),r.show(),e.prop("disabled",!0),v.prev=12,v.next=15,jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+"HtmlCheck",{url:h.val(),norm:k}),type:"POST",
data:"",dataType:"json",cache:!1});case 15:g=v.sent;v.next=21;break;case 18:v.prev=18,v.t0=v["catch"](12),g={err:v.t0.statusText};case 21:r.hide();e.prop("disabled",!1);if(!g.err){v.next=26;break}l.append(seraph_accel.Ui.LogItem("error",g.err));return v.abrupt("return");case 26:for(p in g.list)p=g.list[p],l.append(seraph_accel.Ui.LogItem(p.severity,p.text));case 27:case "end":return v.stop()}},q,this,[[12,18]])}));return O.apply(this,arguments)}var Q=seraph_accel.Wp.Loc.GetApi(),C=Q._x,z=Q.sprintf;
seraph_accel.Settings={_int:{StrItem_OnAdd:function(t){function n(l){(l=l.trim())&&seraph_accel.Ui.TokensList.AddItem(h[0],l)}var q=1<arguments.length&&void 0!==arguments[1]?arguments[1]:",",f=jQuery(t.parentNode).closest(".blck").first(),h=f.find(".vals");f=f.find(".val");q?f.val().split(q).forEach(n):n(f.val());f.val("")},StrItem_OnCopyAll:function(t){seraph_accel.Ui.TokensList.CopyAllItems(jQuery(t.parentNode).closest(".blck").first().find(".vals")[0])},StrItem_OnDelAll:function(t){seraph_accel.Ui.TokensList.DelAllItems(jQuery(t.parentNode).closest(".blck").first().find(".vals")[0])},
OnUpdateCssAuto:function(t){seraph_accel.Ui.ComboShowDependedItems(t,jQuery(t.parentNode).closest(".blck").first().get(0))},OnLogClear:function(t){return E.apply(this,arguments)}}};seraph_accel.Manager={_int:{OnStatOp:function(t,n){return w.apply(this,arguments)},OnCacheOp:function(t,n){return H.apply(this,arguments)},OnCacheOpCancel:function(t,n){return B.apply(this,arguments)},OnPostUpdCancel:function(t){return F.apply(this,arguments)},OnScheUpdCancel:function(t){return G.apply(this,arguments)},
OnExtDbUpdBegin:function(t){return D.apply(this,arguments)},OnExtDbUpdCancel:function(t){return A.apply(this,arguments)},OnQueueDel:function(t,n,q){return K.apply(this,arguments)},OnQueuePause:function(t,n,q){return P.apply(this,arguments)},OnQueueItemCancel:function(t,n,q){return R.apply(this,arguments)},OnDataRefreshInit:function(t,n){return N.apply(this,arguments)},OnDataRefresh:function(t,n){return L.apply(this,arguments)},OnHtmlCheck:function(t){return O.apply(this,arguments)}}};(function(){function t(h){return n.apply(this,
arguments)}function n(){n=_asyncToGenerator(_regenerator.mark(function r(l){var e,k;return _regenerator.wrap(function(g){for(;;)switch(g.prev=g.next){case 0:return e={},g.prev=1,seraph_accel.SelfDiag._int.curAjax=jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+"SelfDiag_"+l,{}),cache:!1,dataType:"json"}),g.next=5,seraph_accel.SelfDiag._int.curAjax;case 5:e=g.sent;delete seraph_accel.SelfDiag._int.curAjax;g.next=14;break;case 9:g.prev=9,g.t0=g["catch"](1),delete seraph_accel.SelfDiag._int.curAjax,
0===g.t0.status?e.hr=seraph_accel.Gen.hr.S_ABORTED:(e.hr=seraph_accel.Gen.hr.E_FAIL,e.descr="HTTP "+g.t0.status),500==g.t0.status&&(k=document.implementation.createHTMLDocument(""),k.documentElement.innerHTML=g.t0.responseText,k=k.body.textContent,k=seraph_accel.Gen.StrReplaceAll(k,"\r",""),k=seraph_accel.Gen.StrReplaceAll(k,["\t","\v"]," "),k=seraph_accel.Gen.StrReplaceAll(k,"\n",". "),(k=seraph_accel.Gen.StrReplaceAllWhileChanging(k,["  ",". . "],[" ",". "]).trim())&&"."!=k&&(e.descr+="<br>"+k));
case 14:return g.abrupt("return",e);case 15:case "end":return g.stop()}},r,this,[[1,9]])}));return n.apply(this,arguments)}function q(){q=_asyncToGenerator(_regenerator.mark(function r(l){var e,k,g,p,v,b,a,c,m,d,x,u=arguments;return _regenerator.wrap(function(y){for(;;)switch(y.prev=y.next){case 0:e=1<u.length&&void 0!==u[1]?u[1]:!1;k=jQuery(l.parentNode).closest(".blck").first();g=k.find(".seraph_accel_spinner");p=k.find('input[type="button"]:not(.cancel)');v=k.find('input[type="button"].cancel');
b=k.find(".log");a=[{id:"3rdPartySettCompat",name:f("TestName_3rdPartySettCompat","admin.SelfDiag","seraphinite-accelerator")},{id:"AsyncRequest",name:f("TestName_AsyncRequest","admin.SelfDiag","seraphinite-accelerator")},{id:"SetMaxExecTime",name:f("TestName_SetMaxExecTime","admin.SelfDiag","seraphinite-accelerator")},{id:"PageOptimize",name:f("TestName_PageOptimize","admin.SelfDiag","seraphinite-accelerator")},{id:"VendorSrv",name:f("TestName_VendorSrv","admin.SelfDiag","seraphinite-accelerator")},
{id:"ExtCache",name:f("TestName_ExtCache","admin.SelfDiag","seraphinite-accelerator")}];b.empty();for(c=0;c<a.length;c++)m=a[c],b.append(seraph_accel.Ui.LogItem("none",seraph_accel.Ui.Tag("strong",m.name?m.name:m.id),!1));if(!e){y.next=11;break}return y.abrupt("return");case 11:g.show(),p.prop("disabled",!0),v.prop("disabled",!1),seraph_accel.SelfDiag._int.inProgress=!0,c=0;case 16:if(!(c<a.length)){y.next=31;break}m=a[c];jQuery(b.children().get(c)).replaceWith(seraph_accel.Ui.LogItem("info",seraph_accel.Ui.Tag("strong",
m.name?m.name:m.id)+f("TestRunning","admin.SelfDiag","seraphinite-accelerator"),!1));y.next=21;return t(m.id);case 21:d=y.sent;x=f("TestSucc","admin.SelfDiag","seraphinite-accelerator");d.hr!=seraph_accel.Gen.hr.S_OK&&(x=seraph_accel.Gen.hr.Succ(d.hr)?d.hr==seraph_accel.Gen.hr.S_ABORTED?f("TestAbort","admin.SelfDiag","seraphinite-accelerator"):d.hr==seraph_accel.Gen.hr.S_FALSE?f("TestNotice","admin.SelfDiag","seraphinite-accelerator"):f("TestWarn","admin.SelfDiag","seraphinite-accelerator"):f("TestError",
"admin.SelfDiag","seraphinite-accelerator"));d.descr&&(x+="<br>"+d.descr);jQuery(b.children().get(c)).replaceWith(seraph_accel.Ui.LogItem(d.hr==seraph_accel.Gen.hr.S_OK?"success":seraph_accel.Gen.hr.Succ(d.hr)?d.hr==seraph_accel.Gen.hr.S_FALSE?"normal":"warning":"error",seraph_accel.Ui.Tag("strong",m.name?m.name:m.id)+x,!1));if(seraph_accel.SelfDiag._int.inProgress){y.next=28;break}return y.abrupt("break",31);case 28:c++;y.next=16;break;case 31:g.hide(),p.prop("disabled",!1),v.prop("disabled",!0);
case 34:case "end":return y.stop()}},r,this)}));return q.apply(this,arguments)}var f=seraph_accel.Wp.Loc.GetApi()._x;seraph_accel.SelfDiag={_int:{OnStart:function(h){return q.apply(this,arguments)},OnCancel:function(h){h=jQuery(h.parentNode).closest(".blck").first();h.find(".seraph_accel_spinner");h.find('input[type="button"]:not(.cancel)');h.find('input[type="button"].cancel').prop("disabled",!0);seraph_accel.SelfDiag._int.inProgress=!1;seraph_accel.SelfDiag._int.curAjax&&seraph_accel.SelfDiag._int.curAjax.abort()},
inProgress:!1}}})()})();
