window.seraph_accel||(window.seraph_accel={});
(function(){seraph_accel.PluginAdmin={AdvertProductsContentInit:function(a,c,b,e,f,g){function d(h,t){var m="";if(Array.isArray(h)&&h.length){m+=seraph_accel.Ui.TagOpen("tr");for(var p=0;p<h.length;p++){var n=h[p];0<p&&0==p%f&&(m+=seraph_accel.Ui.TagClose("tr")+seraph_accel.Ui.TagOpen("tr"));var x=seraph_accel.Ui,C=x.Tag,y=seraph_accel.Ui,D=y.Tag,z=t,q="";var l=n.images;var u=z;if(Array.isArray(l)){for(var v=-1,A=2147483647,w=-1,B=2147483647,r=0;r<l.length;r++){var k=l[r];if(u==k.width){v=r;break}u<
k.width?(k=k.width-u,k<A&&(v=r,A=k)):(k=u-k.width,k<B&&(w=r,B=k))}l=-1!=v?l[v].url:-1!=w?l[w].url:null}else l=null;l&&(q+=seraph_accel.Ui.Tag("td",seraph_accel.Ui.Link(seraph_accel.Ui.Tag("img",null,{"class":"ctlSpaceAfter",width:z,src:l},!0),n.urlInfo,!0),{style:{width:"1px"}}));q+=seraph_accel.Ui.TagOpen("td");q+=seraph_accel.Ui.Tag("h3",n.title,{"class":"ctlSpaceVAfter",style:{"margin-top":0}});q+=seraph_accel.Ui.Tag("div",n.descr);n.urlInfo&&(q+=seraph_accel.Ui.Button(e,!0,null,"ctlSpaceVBefore",
"button",{onclick:"window.open( '"+n.urlInfo+"', '_blank' )"}));q+=seraph_accel.Ui.TagClose("td");n=seraph_accel.Ui.Tag("table",seraph_accel.Ui.Tag("tbody",seraph_accel.Ui.Tag("row",q)));m+=C.call(x,"td",D.call(y,"div",n,{style:{margin:"1em 1em 2em 1em"}}),{"class":"cx-lg-6 cx-xs-12",style:{"vertical-align":"top"}})}for(;p%f;p++)m+=seraph_accel.Ui.Tag("td",null,{"class":"cx-lg-6 cx-xs-12"});m+=seraph_accel.Ui.TagClose("tr");m=seraph_accel.Ui.Tag("table",seraph_accel.Ui.Tag("tbody",m))}jQuery(a).html(m)}
jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(c+"/v1/advert_products",{slug:"accelerator",locale:b}),type:"GET",dataType:"json"}).then(function(h){d(h,g)},function(h){d(null,0)})},SwitchTo:function(a,c,b){function e(d,h){f.hide();g.prop("disabled",!1);d&&window.open(b,"_blank").focus()}a=jQuery(".seraph_accel_switchto");var f=a.find(".seraph_accel_spinner"),g=a.find('input[type="button"]:not(.cancel)');f.show();g.prop("disabled",!0);jQuery.ajax({url:c,type:"POST",data:""}).then(function(d){e(!0)},
function(d){e(!1,"OK"===d.statusText?"PHP error: "+d.responseText:"Backend error: "+d.status+" "+d.statusText)})},RateItCont_Set:function(a,c,b){var e=jQuery("#"+a),f=e.find(".actions"),g=e.find(".seraph_accel_spinner");f.hide();g.show();jQuery.ajax({url:b+"="+(c?"rateItPostpone":"rateItDisable"),type:"POST",data:""}).then(function(d){e.hide()},function(d){f.show();g.hide()})},RateIt_Set:function(a,c){jQuery("#seraph_accel_RateIt_Message .actions").hide();jQuery("#seraph_accel_RateIt_Message .seraph_accel_spinner").show();
jQuery.ajax({url:c+"="+(a?"rateItPostpone":"rateItDisable"),type:"POST",data:""}).then(function(b){seraph_accel.Ui.BannerMsgClose(jQuery("#seraph_accel_RateIt_Message"))},function(b){jQuery("#seraph_accel_RateIt_Message .actions").show();jQuery("#seraph_accel_RateIt_Message .spinner").hide()})},ChangeVersion_Confirm:function(a){jQuery("#seraph_accel_ChangeVersion_Msg .actions").hide();jQuery("#seraph_accel_ChangeVersion_Msg .seraph_accel_spinner").show();jQuery.ajax({url:a+"=changeVersionConfirm",
type:"POST",data:""}).then(function(c){seraph_accel.Ui.BannerMsgClose(jQuery("#seraph_accel_ChangeVersion_Msg"))},function(c){jQuery("#seraph_accel_ChangeVersion_Msg .actions").show();jQuery("#seraph_accel_ChangeVersion_Msg .spinner").hide()})},SettImport:function(a,c,b,e){function f(){d.prop("disabled",!1);g.hide()}if(b){a=jQuery(a.parentNode);var g=a.find(".seraph_accel_spinner"),d=a.find("input.button");d.prop("disabled",!0);g.show();a=new FileReader;a.onabort=function(h){f()};a.onerror=function(h){f()};
a.onload=function(h){jQuery.ajax({url:c+"=settImport&_wpnonce="+e+"&redir="+encodeURIComponent(location.href),type:"POST",contentType:"application/json",data:h.target.result}).then(function(t){t?location=t:location.reload()},function(t){f()})};a.readAsText(b)}},SettExport:function(a,c,b){function e(d){d&&window.saveAs(new Blob([d],{type:"text/json"}),"seraphinite-accelerator-settings.json");g.prop("disabled",!1);f.hide()}a=jQuery(a.parentNode);var f=a.find(".seraph_accel_spinner"),g=a.find("input.button");
g.prop("disabled",!0);f.show();jQuery.ajax({url:c+"=settExport&_wpnonce="+b,type:"POST",data:""}).then(function(d){seraph_accel.Ui.ScriptLoad(document,"https://cdn.jsdelivr.net/npm/file-saver@2.0.5/dist/FileSaver.min.js","file-saver").then(function(){e(d)},function(h){e()})},function(d){e()})},OnSettWizNext:function(a,c){var b=jQuery(a).closest("form");a=jQuery(a.parentNode);var e=b.find(".wizPages");b=e.find(">.active").first();b.get(0)?(c=c?b.next():b.prev(),c.get(0)&&(b.removeClass("active"),b=
c)):b=e.children().first();b.addClass("active");c=!!b.next().get(0);b=!!b.prev().get(0);a.find("input.wizNext").prop("disabled",!c);a.find("input.wizPrev").prop("disabled",!b);c?a.find("input.wizFinish").hide():a.find("input.wizFinish").show()}}})();
